# SFU CMPT 756
# A simple circuit breaker for s2

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cmpt756s2
spec:
  host: cmpt756s2
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 1
    outlierDetection:
        consecutive5xxErrors: 1
        interval: 5s
        baseEjectionTime: 15s
        maxEjectionPercent: 50
